"""Always-on numerical checks against a small fixture generated by R CoPro."""

from pathlib import Path

import numpy as np
import pandas as pd

from copro.correlation import _compute_bidir_corrs_all_cc, _whitened_frob_norm
from copro.gene_space import compute_genespace_objective


REFERENCE = Path(__file__).parent / "r_reference" / "modern_parity.csv"


def _r_values():
    frame = pd.read_csv(REFERENCE)
    return dict(zip(frame["metric"], frame["value"], strict=True))


def test_modern_normalizers_and_gene_objective_match_r_fixture():
    expected = _r_values()
    kernel = np.array([
        [1.2, 0.3, 0.1],
        [0.4, 1.1, 0.2],
        [0.2, 0.5, 0.9],
    ])
    rx = np.array([
        [1.0, 0.2, 0.1],
        [0.2, 0.9, 0.3],
        [0.1, 0.3, 1.1],
    ])
    ry = np.array([
        [0.8, 0.1, 0.2],
        [0.1, 1.2, 0.4],
        [0.2, 0.4, 1.0],
    ])
    np.testing.assert_allclose(
        _whitened_frob_norm(kernel, rx, ry),
        expected["whitened_frob"], rtol=1e-13, atol=1e-13,
    )

    weights = {
        "A": np.array([[0.8], [0.6]]),
        "B": np.array([[-0.3], [np.sqrt(0.91)]]),
    }
    self_covariances = {
        "s1": {"A": np.diag([1.0, 1.5]), "B": np.diag([0.8, 1.2])},
        "s2": {"A": np.diag([1.3, 0.7]), "B": np.diag([1.1, 0.9])},
    }
    cross_covariances = {
        "s1": {"A-B": np.array([[0.7, 0.1], [-0.2, 0.5]])},
        "s2": {"A-B": np.array([[0.4, -0.3], [0.2, 0.8]])},
    }
    observed = compute_genespace_objective(
        weights, self_covariances, cross_covariances,
        ["s1", "s2"], ["A", "B"],
    )
    np.testing.assert_allclose(
        observed, expected["gene_space_objective"], rtol=1e-13, atol=1e-13,
    )


def test_modern_bidirectional_correlations_match_r_fixture():
    expected = _r_values()
    kernel = np.array([
        [1.2, 0.3, 0.1],
        [0.4, 1.1, 0.2],
        [0.2, 0.5, 0.9],
    ])
    scores_a = np.array([[-1.0, 0.2], [0.4, 1.1], [1.3, -0.5]])
    scores_b = np.array([[0.8, -0.4], [-1.1, 1.2], [1.6, 0.5]])

    observed_none = _compute_bidir_corrs_all_cc(
        scores_a, scores_b, kernel, "none"
    )
    observed_row_col = _compute_bidir_corrs_all_cc(
        scores_a, scores_b, kernel, "row_or_col"
    )
    np.testing.assert_allclose(
        observed_none,
        [expected["bidir_none_cc1"], expected["bidir_none_cc2"]],
        rtol=1e-13, atol=1e-13,
    )
    np.testing.assert_allclose(
        observed_row_col,
        [expected["bidir_row_col_cc1"], expected["bidir_row_col_cc2"]],
        rtol=1e-13, atol=1e-13,
    )
